<?php
namespace resoul\imdb\model\enum;

enum DistributorEnum: int
{
    case TWENTIETH_CENTURY_FOX = 1;
    case SONY_PICTURES = 2;
    case A24 = 3;
    case WARNER_BROS = 4;
    case UNIVERSAL_PICTURES = 5;
    case COLUMBIA_PICTURES = 6;
    case PARAMOUNT_PICTURES = 7;
    case UNITED_ARTISTS = 8;
    case METRO_GOLDWYN_MAYER = 9;
    case AIP = 10;
    case EMBASSY_PICTURES = 11;
    case WALT_DISNEY_STUDIOS = 12;
    case JENSEN_FARLEY_PICTURES = 13;
    case FILMWAYS = 14;
    case GROUP_ONE = 15;
    case ORION_PICTURES = 16;
    case FILM_VENTURES = 17;
    case ATLANTIC_RELEASING = 18;
    case CROWN = 19;
    case NEW_WORLD_PICTURES = 20;
    case TRISTAR_PICTURES = 21;
    case CANNON_FILM = 22;
    case NEW_LINE_CINEMA = 23;
    case SAMUEL_GOLDWIN_COMPANY = 24;
    case ISLAND_ALIVE = 25;
    case EMPIRE_PICTURES = 26;
    case DE_LAURENTIS = 27;
    case GALAXY = 28;
    case NEW_CENTURY = 29;
    case PALISADES = 30;
    case VESTRON_PICTURES = 31;
    case LORIMAR_PICTURES = 32;
    case TRANS_WORLD = 33;
    case MIRAMAX = 34;
    case SHAPIRO_GLICKENHAUS = 35;
    case HEMDALE = 36;
    case TWENTY_ONE_CENTURY_FILM = 37;
    case TRIUMPH = 38;
    case SONY_PICTURES_RELEASING = 39;
    case STUDIO_THREE = 40;
    case INTERSTAR = 41;
    case TRIMARK_PICTURES = 42;
    case GRAMERCY_PICTURES = 43;
    case SAVOY_PICTURES = 44;
    case KEYSTONE = 45;
    case DIMENSION_FILMS = 46;
    case FOX_SEARCHLIGHT = 47;
    case DREAMWORKS_DISTRIBUTION = 48;
    case LIVE = 49;
    case POLYGRAM = 50;
    case OCTOBER = 51;
    case ARTISAN = 52;
    case USA = 53;
    case PROVIDENCE = 54;
    case DESTINATION = 55;
    case LIONSGATE = 56;

    case SONY_PICTURES_CLASSIC = 57;
    case FOCUS_FEATURES = 58;
    case SCREEN_GEMS = 59;
    case REVOLUTION_STUDIOS = 60;
    case NEWMARKET_FILMS = 61;
    case IFC = 62;
    case IDP = 63;
    case ROGUE_PICTURES = 64;
    case MAGNOLIA_PICTURES = 65;
    case WARNER_PICTURES = 66;
    case PARAMOUNT_CLASSIC = 67;
    case WEINSTEIN_COMPANY = 68;
    case ROCKY_MOUNTAIN_PICTURES = 69;

    case FREESTYLE = 70;
    case PICTUREHOUSE = 71;
    case DRAGON_DYNASTY = 72;
    case DREAMWORKS = 73;
    case YARI = 74;
    case MGM = 75;
    case EIGHT_ENTERTAINMENT = 76;
    case FOX_ATOMIC = 77;
    case PARAMOUNT_VANTAGE = 78;
    case SONY_BMG = 79;
    case SUMMIT = 80;
    case OVERTURE_FILMS = 81;
    case VIVENDI_ENTERTAINMENT = 82;
    case CBS = 83;
    case RELIANCE_BIG_PICTURES = 84;
    case RELATIVITY_MEDIA = 85;
    case ROADSIDE_ATTRACTIONS = 86;

    public static function getLabels(): array
    {
        return [
            DistributorEnum::TWENTIETH_CENTURY_FOX->value => 'Twentieth Century Fox',
            DistributorEnum::SONY_PICTURES->value => 'Sony Pictures',
            DistributorEnum::A24->value => 'A24',
            DistributorEnum::WARNER_BROS->value => 'Warner Bros.',
            DistributorEnum::UNIVERSAL_PICTURES->value => 'Universal Pictures',
            DistributorEnum::COLUMBIA_PICTURES->value => 'Columbia Pictures',
            DistributorEnum::PARAMOUNT_PICTURES->value => 'Paramount Pictures',
            DistributorEnum::UNITED_ARTISTS->value => 'United Artists',
            DistributorEnum::METRO_GOLDWYN_MAYER->value => 'Metro-Goldwyn-Mayer (MGM)',
            DistributorEnum::MGM->value => 'MGM',
            DistributorEnum::AIP->value => 'American International Pictures (AIP)',
            DistributorEnum::EMBASSY_PICTURES->value => 'Embassy Pictures',
            DistributorEnum::WALT_DISNEY_STUDIOS->value => 'Walt Disney Studios Motion Pictures',
            DistributorEnum::JENSEN_FARLEY_PICTURES->value => 'Jensen Farley Pictures',
            DistributorEnum::FILMWAYS->value => 'Filmways',
            DistributorEnum::GROUP_ONE->value => 'Group 1',
            DistributorEnum::ORION_PICTURES->value => 'Orion Pictures',
            DistributorEnum::FILM_VENTURES->value => 'Film Ventures International',
            DistributorEnum::ATLANTIC_RELEASING->value => 'Atlantic Releasing Corporation',
            DistributorEnum::CROWN->value => 'Crown',
            DistributorEnum::NEW_WORLD_PICTURES->value => 'New World Pictures',
            DistributorEnum::TRISTAR_PICTURES->value => 'TriStar Pictures',
            DistributorEnum::CANNON_FILM->value => 'Cannon Film Distributors',
            DistributorEnum::NEW_LINE_CINEMA->value => 'New Line Cinema',
            DistributorEnum::SAMUEL_GOLDWIN_COMPANY->value => 'The Samuel Goldwyn Company',
            DistributorEnum::ISLAND_ALIVE->value => 'Island Alive',
            DistributorEnum::EMPIRE_PICTURES->value => 'Empire Pictures',
            DistributorEnum::DE_LAURENTIS->value => 'De Laurentiis Entertainment Group (DEG)',
            DistributorEnum::GALAXY->value => 'Galaxy International',
            DistributorEnum::NEW_CENTURY->value => 'New Century',
            DistributorEnum::PALISADES->value => 'Palisades Entertainment Corporation',
            DistributorEnum::VESTRON_PICTURES->value => 'Vestron Pictures',
            DistributorEnum::LORIMAR_PICTURES->value => 'Lorimar Motion Pictures',
            DistributorEnum::TRANS_WORLD->value => 'Trans World Entertainment (TWE)',
            DistributorEnum::MIRAMAX->value => 'Miramax',
            DistributorEnum::SHAPIRO_GLICKENHAUS->value => 'Shapiro-Glickenhaus Entertainment',
            DistributorEnum::HEMDALE->value => 'Hemdale',
            DistributorEnum::TWENTY_ONE_CENTURY_FILM->value => '21st Century Film Corporation',
            DistributorEnum::TRIUMPH->value => 'Triumph Releasing Corporation',
            DistributorEnum::SONY_PICTURES_RELEASING->value => 'Sony Pictures Releasing',
            DistributorEnum::STUDIO_THREE->value => 'Studio Three',
            DistributorEnum::INTERSTAR->value => 'Interstar',
            DistributorEnum::TRIMARK_PICTURES->value => 'Trimark Pictures',
            DistributorEnum::GRAMERCY_PICTURES->value => 'Gramercy Pictures (I)',
            DistributorEnum::SAVOY_PICTURES->value => 'Savoy Pictures',
            DistributorEnum::KEYSTONE->value => 'Keystone Entertainment Inc.',
            DistributorEnum::DIMENSION_FILMS->value => 'Dimension Films',
            DistributorEnum::FOX_SEARCHLIGHT->value => 'Fox Searchlight',
            DistributorEnum::DREAMWORKS_DISTRIBUTION->value => 'DreamWorks Distribution',
            DistributorEnum::LIVE->value => 'Live',
            DistributorEnum::POLYGRAM->value => 'PolyGram',
            DistributorEnum::OCTOBER->value => 'October Films',
            DistributorEnum::ARTISAN->value => 'Artisan Entertainment',
            DistributorEnum::USA->value => 'USA Films',
            DistributorEnum::PROVIDENCE->value => 'Providence Entertainment',
            DistributorEnum::DESTINATION->value => 'Destination Films',
            DistributorEnum::LIONSGATE->value => 'Lionsgate Films',
            DistributorEnum::SONY_PICTURES_CLASSIC->value => 'Sony Pictures Classics',
            DistributorEnum::FOCUS_FEATURES->value => 'Focus Features',
            DistributorEnum::SCREEN_GEMS->value => 'Screen Gems',
            DistributorEnum::REVOLUTION_STUDIOS->value => 'Revolution Studios',
            DistributorEnum::NEWMARKET_FILMS->value => 'Newmarket Films',
            DistributorEnum::IFC->value => 'IFC Films',
            DistributorEnum::IDP->value => 'IDP Distribution',
            DistributorEnum::ROGUE_PICTURES->value => 'Rogue Pictures',
            DistributorEnum::MAGNOLIA_PICTURES->value => 'Magnolia Pictures',
            DistributorEnum::WARNER_PICTURES->value => 'Warner Independent Pictures (WIP)',
            DistributorEnum::PARAMOUNT_CLASSIC->value => 'Paramount Classics',
            DistributorEnum::WEINSTEIN_COMPANY->value => 'The Weinstein Company',
            DistributorEnum::ROCKY_MOUNTAIN_PICTURES->value => 'Rocky Mountain Pictures',
            DistributorEnum::FREESTYLE->value => 'Freestyle Releasing',
            DistributorEnum::PICTUREHOUSE->value => 'Picturehouse',
            DistributorEnum::DRAGON_DYNASTY->value => 'Dragon Dynasty',
            DistributorEnum::DREAMWORKS->value => 'DreamWorks',
            DistributorEnum::YARI->value => 'Yari Film Group Releasing',
            DistributorEnum::EIGHT_ENTERTAINMENT->value => '8x Entertainment',
            DistributorEnum::FOX_ATOMIC->value => 'Fox Atomic',
            DistributorEnum::PARAMOUNT_VANTAGE->value => 'Paramount Vantage',
            DistributorEnum::SONY_BMG->value => 'Sony BMG',
            DistributorEnum::SUMMIT->value => 'Summit Entertainment',
            DistributorEnum::OVERTURE_FILMS->value => 'Overture Films',
            DistributorEnum::VIVENDI_ENTERTAINMENT->value => 'Vivendi Entertainment',
            DistributorEnum::CBS->value => 'CBS Films',
            DistributorEnum::RELIANCE_BIG_PICTURES->value => 'Reliance Big Pictures',
            DistributorEnum::RELATIVITY_MEDIA->value => 'Relativity Media',
            DistributorEnum::ROADSIDE_ATTRACTIONS->value => 'Roadside Attractions',
        ];
    }
}
